/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogInsertProduto.java
 *
 * Created on 23/Dez/2010, 2:05:48
 */

package farmaciabd;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Miguel
 */
public class JDialogInsertProduto extends java.awt.Dialog {

    ResultSet rSet = null;

    /** Creates new form JDialogInsertProduto */
    public JDialogInsertProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanelinserirProduto = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jComboBox11 = new javax.swing.JComboBox();
        jComboBox12 = new javax.swing.JComboBox();
        jPanelLote = new javax.swing.JPanel();
        jLabelCodProdutoIns = new javax.swing.JLabel();
        jTextFieldCodProdutoIns = new javax.swing.JTextField();
        jLabelNomeGenIns = new javax.swing.JLabel();
        jTextFieldNomeGenIns = new javax.swing.JTextField();
        jLabelNomeMedicamentoIns = new javax.swing.JLabel();
        jTextFieldNomeDoMedicamento = new javax.swing.JTextField();
        jLabelQuantidadeIns = new javax.swing.JLabel();
        jLabelFaixaEtariaIns = new javax.swing.JLabel();
        jLabelRegistoInfarmedIns = new javax.swing.JLabel();
        jLabelAreaTerapeuticaIns = new javax.swing.JLabel();
        jComboBoxAreaTerapeuticaIns = new javax.swing.JComboBox();
        jLabelLoteIns = new javax.swing.JLabel();
        jTextFieldLoteIns = new javax.swing.JTextField();
        jLabelDosagemIns = new javax.swing.JLabel();
        jTextFieldDosagemIns = new javax.swing.JTextField();
        jLabelTemperaturaIns = new javax.swing.JLabel();
        jComboBoxTemperaturaIns = new javax.swing.JComboBox();
        jLabelPrecoIns = new javax.swing.JLabel();
        jTextFieldPrecoIns = new javax.swing.JTextField();
        jLabelAdministracao = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextFieldRegistoInfarmedIns = new javax.swing.JTextField();
        jComboBoxFaixaEtaria = new javax.swing.JComboBox();
        jComboBoxAdministracaoIns = new javax.swing.JComboBox();
        jSpinnerQuantidadeIns = new javax.swing.JSpinner();
        jRadioButtonReceitaSimIns = new javax.swing.JRadioButton();
        jRadioButtonReceitaNaoIns = new javax.swing.JRadioButton();
        jRadioButtonGenericoSim = new javax.swing.JRadioButton();
        jRadioButtonGenericoNao = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jTextField13 = new javax.swing.JTextField();
        jButtonLimparCamposInsertproduto = new javax.swing.JButton();
        jButtonAdicionarProduto = new javax.swing.JButton();
        jButtonCancelarIns = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Constituintes"));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox2, 0, 300, Short.MAX_VALUE)
            .addComponent(jComboBox5, 0, 300, Short.MAX_VALUE)
            .addComponent(jComboBox6, 0, 300, Short.MAX_VALUE)
            .addComponent(jComboBox7, 0, 300, Short.MAX_VALUE)
            .addComponent(jComboBox8, 0, 300, Short.MAX_VALUE)
            .addComponent(jComboBox9, 0, 300, Short.MAX_VALUE)
            .addComponent(jComboBox10, 0, 300, Short.MAX_VALUE)
            .addComponent(jComboBox11, 0, 300, Short.MAX_VALUE)
            .addComponent(jComboBox12, 0, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelLote.setBorder(javax.swing.BorderFactory.createTitledBorder("Ficha do Produto"));

        jLabelCodProdutoIns.setText("Código do Produto");

        jLabelNomeGenIns.setText("Nome Genérico");

        jLabelNomeMedicamentoIns.setText("Nome do Medicamento");

        jLabelQuantidadeIns.setText("Quantidade");

        jLabelFaixaEtariaIns.setText("Faixa Etaria");

        jLabelRegistoInfarmedIns.setText("Registo Infarmed");

        jLabelAreaTerapeuticaIns.setText("Área Terapeutica");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ObjectProperty.create(), jComboBoxAreaTerapeuticaIns, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);

        try {     
            rSet = Areas_Terapeuticas.queryAreasTerapeuticas(); 

            //DefaultListModel model = new DefaultListModel();     

            while (rSet.next())         
            jComboBoxAreaTerapeuticaIns.addItem(rSet.getString(1));     
        }

        catch (SQLException ex) { 
            Logger.getLogger(JPrincipal.class.getName()).log(Level.SEVERE, null, ex); 
        }

        jLabelLoteIns.setText("Lote");

        jLabelDosagemIns.setText("Dosagem");

        jLabelTemperaturaIns.setText("Temperatura");

        try {     
            rSet = Temperaturas.queryTemperaturas(); 

            while (rSet.next())         
            jComboBoxTemperaturaIns.addItem(rSet.getString(1));     
        }

        catch (SQLException ex) { 
            Logger.getLogger(JPrincipal.class.getName()).log(Level.SEVERE, null, ex); 
        }

        jLabelPrecoIns.setText("Preço (€)");

        jLabelAdministracao.setText("Administração");

        jLabel13.setText("Precisa de Receita?");

        jLabel14.setText("É Genérico?");

        jLabel15.setText("Formato");

        try {     
            rSet = FaixasEtarias.queryFaixasEtarias(); 

            //DefaultListModel model = new DefaultListModel();     

            while (rSet.next())         
            jComboBoxFaixaEtaria.addItem(rSet.getString(1));     
        }

        catch (SQLException ex) { 
            Logger.getLogger(JPrincipal.class.getName()).log(Level.SEVERE, null, ex); 
        }
        jComboBoxFaixaEtaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFaixaEtariaActionPerformed(evt);
            }
        });

        try {     
            rSet = Administracoes.queryAdministracoes(); 

            while (rSet.next())         
            jComboBoxAdministracaoIns.addItem(rSet.getString(1));     
        }

        catch (SQLException ex) { 
            Logger.getLogger(JPrincipal.class.getName()).log(Level.SEVERE, null, ex); 
        }

        jRadioButtonReceitaSimIns.setText("Sim");

        jRadioButtonReceitaNaoIns.setText("Não");

        jRadioButtonGenericoSim.setText("Sim");

        jRadioButtonGenericoNao.setText("Não");

        javax.swing.GroupLayout jPanelLoteLayout = new javax.swing.GroupLayout(jPanelLote);
        jPanelLote.setLayout(jPanelLoteLayout);
        jPanelLoteLayout.setHorizontalGroup(
            jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoteLayout.createSequentialGroup()
                .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomeMedicamentoIns)
                    .addComponent(jLabelCodProdutoIns)
                    .addComponent(jLabelNomeGenIns)
                    .addComponent(jLabelQuantidadeIns)
                    .addComponent(jLabelFaixaEtariaIns)
                    .addComponent(jLabelRegistoInfarmedIns)
                    .addComponent(jLabelAreaTerapeuticaIns)
                    .addComponent(jLabelLoteIns)
                    .addComponent(jLabelDosagemIns)
                    .addComponent(jLabelTemperaturaIns)
                    .addComponent(jLabelPrecoIns)
                    .addComponent(jLabelAdministracao)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinnerQuantidadeIns, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(jComboBoxAdministracaoIns, javax.swing.GroupLayout.Alignment.LEADING, 0, 303, Short.MAX_VALUE)
                    .addComponent(jComboBoxFaixaEtaria, javax.swing.GroupLayout.Alignment.LEADING, 0, 303, Short.MAX_VALUE)
                    .addComponent(jTextFieldRegistoInfarmedIns, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(jTextFieldPrecoIns, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(jComboBoxTemperaturaIns, javax.swing.GroupLayout.Alignment.LEADING, 0, 303, Short.MAX_VALUE)
                    .addComponent(jTextFieldDosagemIns, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(jTextFieldLoteIns, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(jComboBoxAreaTerapeuticaIns, javax.swing.GroupLayout.Alignment.LEADING, 0, 303, Short.MAX_VALUE)
                    .addComponent(jTextFieldCodProdutoIns, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(jTextFieldNomeGenIns, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(jTextFieldNomeDoMedicamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addGroup(jPanelLoteLayout.createSequentialGroup()
                        .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLoteLayout.createSequentialGroup()
                        .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLoteLayout.createSequentialGroup()
                                .addComponent(jRadioButtonReceitaSimIns)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoteLayout.createSequentialGroup()
                                .addComponent(jRadioButtonGenericoSim)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonGenericoNao)
                            .addComponent(jRadioButtonReceitaNaoIns))
                        .addGap(143, 143, 143))))
        );
        jPanelLoteLayout.setVerticalGroup(
            jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoteLayout.createSequentialGroup()
                .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodProdutoIns)
                    .addComponent(jTextFieldCodProdutoIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeGenIns)
                    .addComponent(jTextFieldNomeGenIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeMedicamentoIns)
                    .addComponent(jTextFieldNomeDoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuantidadeIns)
                    .addComponent(jSpinnerQuantidadeIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFaixaEtariaIns)
                    .addComponent(jComboBoxFaixaEtaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegistoInfarmedIns)
                    .addComponent(jTextFieldRegistoInfarmedIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAreaTerapeuticaIns)
                    .addComponent(jComboBoxAreaTerapeuticaIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLoteIns)
                    .addComponent(jTextFieldLoteIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDosagemIns)
                    .addComponent(jTextFieldDosagemIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTemperaturaIns)
                    .addComponent(jComboBoxTemperaturaIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPrecoIns)
                    .addComponent(jTextFieldPrecoIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdministracao)
                    .addComponent(jComboBoxAdministracaoIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jRadioButtonReceitaSimIns)
                    .addComponent(jRadioButtonReceitaNaoIns))
                .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLoteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(jPanelLoteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonGenericoSim)
                            .addComponent(jRadioButtonGenericoNao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Mais Informações"));

        jTextField13.setBorder(javax.swing.BorderFactory.createTitledBorder("URL do Folheto Informativo"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonLimparCamposInsertproduto.setText("Limpar Campos");

        jButtonAdicionarProduto.setText("Adicionar Produto");
        jButtonAdicionarProduto.setActionCommand("Adicionar");

        jButtonCancelarIns.setText("Cancelar");
        jButtonCancelarIns.setActionCommand("");
        jButtonCancelarIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarInsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelinserirProdutoLayout = new javax.swing.GroupLayout(jPanelinserirProduto);
        jPanelinserirProduto.setLayout(jPanelinserirProdutoLayout);
        jPanelinserirProdutoLayout.setHorizontalGroup(
            jPanelinserirProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelinserirProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelinserirProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelinserirProdutoLayout.createSequentialGroup()
                        .addComponent(jPanelLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelinserirProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelinserirProdutoLayout.createSequentialGroup()
                        .addComponent(jButtonLimparCamposInsertproduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 442, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarIns)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdicionarProduto))))
        );
        jPanelinserirProdutoLayout.setVerticalGroup(
            jPanelinserirProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelinserirProdutoLayout.createSequentialGroup()
                .addGroup(jPanelinserirProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelinserirProdutoLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelinserirProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimparCamposInsertproduto)
                    .addComponent(jButtonAdicionarProduto)
                    .addComponent(jButtonCancelarIns))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        add(jPanelinserirProduto, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButtonCancelarInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarInsActionPerformed
        JDialogInsertProduto.this.dispose();
    }//GEN-LAST:event_jButtonCancelarInsActionPerformed

    private void jComboBoxFaixaEtariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFaixaEtariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFaixaEtariaActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogInsertProduto dialog = new JDialogInsertProduto(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarProduto;
    private javax.swing.JButton jButtonCancelarIns;
    private javax.swing.JButton jButtonLimparCamposInsertproduto;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JComboBox jComboBoxAdministracaoIns;
    private javax.swing.JComboBox jComboBoxAreaTerapeuticaIns;
    private javax.swing.JComboBox jComboBoxFaixaEtaria;
    private javax.swing.JComboBox jComboBoxTemperaturaIns;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabelAdministracao;
    private javax.swing.JLabel jLabelAreaTerapeuticaIns;
    private javax.swing.JLabel jLabelCodProdutoIns;
    private javax.swing.JLabel jLabelDosagemIns;
    private javax.swing.JLabel jLabelFaixaEtariaIns;
    private javax.swing.JLabel jLabelLoteIns;
    private javax.swing.JLabel jLabelNomeGenIns;
    private javax.swing.JLabel jLabelNomeMedicamentoIns;
    private javax.swing.JLabel jLabelPrecoIns;
    private javax.swing.JLabel jLabelQuantidadeIns;
    private javax.swing.JLabel jLabelRegistoInfarmedIns;
    private javax.swing.JLabel jLabelTemperaturaIns;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelLote;
    private javax.swing.JPanel jPanelinserirProduto;
    private javax.swing.JRadioButton jRadioButtonGenericoNao;
    private javax.swing.JRadioButton jRadioButtonGenericoSim;
    private javax.swing.JRadioButton jRadioButtonReceitaNaoIns;
    private javax.swing.JRadioButton jRadioButtonReceitaSimIns;
    private javax.swing.JSpinner jSpinnerQuantidadeIns;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextFieldCodProdutoIns;
    private javax.swing.JTextField jTextFieldDosagemIns;
    private javax.swing.JTextField jTextFieldLoteIns;
    private javax.swing.JTextField jTextFieldNomeDoMedicamento;
    private javax.swing.JTextField jTextFieldNomeGenIns;
    private javax.swing.JTextField jTextFieldPrecoIns;
    private javax.swing.JTextField jTextFieldRegistoInfarmedIns;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
